routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', 'PertanyaanController@index');
// Route::get('/pertanyaan', 'PertanyaanController@index');
// Route::get('/pertanyaan/create', 'PertanyaanController@create');
// Route::post('/pertanyaan', 'PertanyaanController@store');
// Route::get('/pertanyaan/{id}', 'PertanyaanController@show');
// Route::get('/pertanyaan/{id}/edit', 'PertanyaanController@edit');
// Route::put('/pertanyaan/{id}', 'PertanyaanController@update');
// Route::delete('/pertanyaan/{id}', 'PertanyaanController@destroy');

// route resource
Route::resource('pertanyaan', 'PertanyaanController');

app/Pertanyaan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pertanyaan extends Model
{
    protected $table = "pertanyaan";

    protected $guarded = [];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PertanyaanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Pertanyaan;

class PertanyaanController extends Controller
{
    public function index()
    {
        // versi query builder
        // $pertanyaan = DB::table('pertanyaan')->get();

        // versi olequent model orm
        $pertanyaan = Pertanyaan::all();
        return view('pertanyaan.index', compact('pertanyaan'));
    }

    public function create()
    {
        return view('pertanyaan.create');
    }

    public function store(Request $request)
    {
        // dd($request->all());
        $request->validate([
            'judul' => 'required',
            'isi' => 'required',
            'tanggal_dibuat' => 'required',
            'tanggal_diperbaharui' => 'required'
        ]);

        // versi query builder
        // $query = DB::table('pertanyaan')->insert([
        //     'judul' => $request['judul'],
        //     'isi' => $request['isi'],
        //     'tanggal_dibuat' => $request['tanggal_dibuat'],
        //     'tanggal_diperbaharui' => $request['tanggal_diperbaharui'],
        //     'jawaban_tepat_id' => $request['jawaban_tepat_id'],
        //     'profil_id' => $request['profil_id']
        // ]);

        // versi olequent model orm
        $pertanyaan = Pertanyaan::create([
            'judul' => $request['judul'],
            'isi' => $request['isi'],
            'tanggal_dibuat' => $request['tanggal_dibuat'],
            'tanggal_diperbaharui' => $request['tanggal_diperbaharui'],
            'jawaban_tepat_id' => $request['jawaban_tepat_id'],
            'profil_id' => $request['profil_id']
        ]);

        return redirect('/pertanyaan')->with('success', 'Pertanyaan Baru Berhasil Disimpan!');
    }

    public function show($id)
    {
        // versi query builder
        // $pertanyaan = DB::table('pertanyaan')->where('id', $id)->first();

        // versi olequent model orm
        $pertanyaan = Pertanyaan::find($id);

        return view('pertanyaan.show', compact('pertanyaan'));
    }

    public function edit($id)
    {
        // versi query builder
        // $pertanyaan = DB::table('pertanyaan')->where('id', $id)->first();

        // versi olequent model orm
        $pertanyaan = Pertanyaan::find($id);

        return view('pertanyaan.edit', compact('pertanyaan'));
    }

    public function update($id, Request $request)
    {
        $request->validate([
            'judul' => 'required',
            'isi' => 'required',
            'tanggal_dibuat' => 'required',
            'tanggal_diperbaharui' => 'required'
        ]);

        // versi query builder
        // $query = DB::table('pertanyaan')
        //             ->where('id', $id)
        //             ->update([
        //                 'judul' => $request['judul'],
        //                 'isi' => $request['isi'],
        //                 'tanggal_dibuat' => $request['tanggal_dibuat'],
        //                 'tanggal_diperbaharui' => $request['tanggal_diperbaharui'],
        //                 'jawaban_tepat_id' => $request['jawaban_tepat_id'],
        //                 'profil_id' => $request['profil_id']
        //             ]);

        // versi olequent model orm
        $pertanyaan = Pertanyaan::find($id)->update([
            "judul" => $request['judul'],
            'isi' => $request['isi'],
            'tanggal_dibuat' => $request['tanggal_dibuat'],
            'tanggal_diperbaharui' => $request['tanggal_diperbaharui'],
            'jawaban_tepat_id' => $request['jawaban_tepat_id'],
            'profil_id' => $request['profil_id']
        ]);

        return redirect('/pertanyaan')->with('update', 'Berhasil Update Pertanyaan!');
    }

    // public function destroy($id)
    // {
    //     // versi query builder
    //     // $query = DB::table('pertanyaan')->where('id', $id)->delete();

    //     // versi olequent model orm
    //     Pertanyaan::destroy($id);

    //     return redirect('/pertanyaan')->with('delete', 'Pertanyaan Berhasil Dihapus!');
    // }

    public function destroy(Request $request, $id)
    {
        if ($request->ajax()){
            $user = Pertanyaan::findOrFail($id);

            if ($user){
                $user->delete();
                return response()->json(array('success' => true));
            }
        }
    }
}

resources/views/adminlte/master.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Blank Page</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link rel="stylesheet" href=" {{ asset('/adminlte/plugins/fontawesome-free/css/all.min.css')}} ">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{{ asset('/adminlte/dist/css/adminlte.min.css')}}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/10.12.6/sweetalert2.min.css" integrity="sha512-EeZYT52DgUwGU45iNoywycYyJW/C2irAZhp2RZAA0X4KtgE4XbqUl9zXydANcIlEuF+BXpsooxzkPW081bqoBQ==" crossorigin="anonymous" />
</head>

<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <!-- Navbar -->
        @include('adminlte.partials.navbar')
        <!-- /.navbar -->

        <!-- Main Sidebar Container -->
        @include('adminlte.partials.sidebar')

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            @include('adminlte.partials.wrapper')

            <!-- Main content -->
            <section class="content">
                @yield('content')
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->

        <footer class="main-footer">
            <div class="float-right d-none d-sm-block">
                <b>Version</b> 3.0.5
            </div>
            <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong> All rights
            reserved.
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->

    <!-- jQuery -->
    <script src="{{ asset('/adminlte/plugins/jquery/jquery.min.js')}}"></script>
    <!-- Bootstrap 4 -->
    <script src="{{ asset('/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
    <!-- AdminLTE App -->
    <script src="{{ asset('/adminlte/dist/js/adminlte.min.js')}}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{{ asset('/adminlte/dist/js/demo.js')}}"></script>

    {{-- Swal --}}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/10.12.6/sweetalert2.min.js" integrity="sha512-cNaY7ThUQSAxQRW5wvhRBLheHFFAVjnXFFD3K8H7gI1xq+W+tVz9ntPNyoioKpJFc7DyYLWCFem3KBthn7XJTQ==" crossorigin="anonymous"></script>
    <!-- Optional: include a polyfill for ES6 Promises for IE11 -->
    <script src="https://cdn.jsdelivr.net/npm/promise-polyfill"></script>

    <script>
        var items = ["halo", "ini", "items", "di", "master"];
        $(function() {
            var timeout = 3000; // in miliseconds (3*1000)
            $('.alert').delay(timeout).fadeOut(400);
        });

    </script>

    @stack('scripts')

</body>

</html>

resources/views/adminlte/partials/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{{ route('pertanyaan.index') }}" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{{ route('pertanyaan.create') }}" class="nav-link">Create New Pertanyaan</a>
        </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
        <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
            <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </form>

</nav>

resources/views/adminlte/partials/sidebar.blade.php
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{{ route('pertanyaan.index') }}" class="brand-link">
        <img src="{{ asset('/adminlte/dist/img/AdminLTELogo.png') }}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
            style="opacity: .8">
        <span class="brand-text font-weight-light">AdminLTE 3</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{ asset('/adminlte/dist/img/user2-160x160.jpg') }}" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="{{ route('pertanyaan.index') }}" class="d-block">Alexander Pierce</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-table"></i>
                        <p>
                            Pertanyaan
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{ route('pertanyaan.index') }}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Home</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('pertanyaan.create') }}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Create New Pertanyaan</p>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

resources/views/adminlte/partials/wrapper.blade.php
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>@yield('title')</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/pertanyaan">Home</a></li>
                    <li class="breadcrumb-item active">@yield('title')</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

resources/views/pertanyaan/create.blade.php
@extends('adminlte.master')

@section('title')
    Form Create New Pertanyaan
@endsection

@section('content')
    <div class="ml-3 mt-3">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Create New Pertanyaan</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form role="form" action="{{ route('pertanyaan.store') }}" method="POST">
                @csrf
                <div class="card-body">
                    @error('judul')
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            {{ $message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    @enderror
                    @error('isi')
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            {{ $message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    @enderror
                    @error('tanggal_dibuat')
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            {{ $message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    @enderror
                    @error('tanggal_diperbaharui')
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            {{ $message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    @enderror
                    <div class="form-group">
                        <label for="judul">Judul Pertanyaan</label>
                        <input type="text" class="form-control" id="judul" name="judul" value="{{ old('judul', '') }}" placeholder="Masukkan Judul Pertanyaan">
                        {{-- @error('judul')
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                {{ $message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @enderror --}}
                    </div>
                    <div class="form-group">
                        <label for="isi">Isi Pertanyaan</label>
                        <textarea class="form-control" name="isi" id="isi" rows="5" value="{{ old('isi', '') }}" placeholder="Masukkan Isi Pertanyaan">{{ old('isi', '') }}</textarea>
                        {{-- @error('isi')
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                {{ $message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @enderror --}}
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <!-- textarea -->
                            <div class="form-group">
                                <label for="tanggal_dibuat">Tanggal Dibuat</label>
                                <input type="date" class="form-control" id="tanggal_dibuat" name="tanggal_dibuat"
                                    value="{{ old('tanggal_dibuat', '') }}" placeholder="Masukkan Tanggal Dibuat">
                                {{-- @error('tanggal_dibuat')
                                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                        {{ $message }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                @enderror --}}
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="tanggal_diperbaharui">Tanggal Diperbaharui</label>
                                <input type="date" class="form-control" id="tanggal_diperbaharui"
                                    name="tanggal_diperbaharui" value="{{ old('tanggal_diperbaharui', '') }}"
                                    placeholder="Masukkan Tanggal Diperbaharui">
                                {{-- @error('tanggal_diperbaharui')
                                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                        {{ $message }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                @enderror --}}
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="jawaban_tepat_id">ID Jawaban Tepat</label>
                        <input type="number" class="form-control" id="jawaban_tepat_id" name="jawaban_tepat_id"
                            value="{{ old('jawaban_tepat_id', '') }}" placeholder="Masukkan ID Jawaban Tepat">
                        {{-- @error('jawaban_tepat_id')
                                <div class="alert alert-danger">{{ $message }}</div>
                    @enderror --}}
                    </div>
                    <div class="form-group">
                        <label for="profil_id">ID Profil</label>
                        <input type="number" class="form-control" id="profil_id" name="profil_id"
                            value="{{ old('profil_id', '') }}" placeholder="Masukkan ID Profil">
                        {{-- @error('profil_id')
                                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror --}}
                    </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                    <a class="btn btn-warning mr-1" href="{{ route('pertanyaan.index') }}">Batal</a>
                    <button type="submit" class="btn btn-primary">Create</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/pertanyaan/edit.blade.php
@extends('adminlte.master')

@section('title')
    Form Edit Pertanyaan
@endsection

@section('content')
    <div class="ml-3 mt-3">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Edit Pertanyaan ID - {{ $pertanyaan->id }}</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form role="form" action="{{ route('pertanyaan.update', ['pertanyaan' => $pertanyaan->id]) }}" method="POST">
                @csrf
                @method('PUT')
                <div class="card-body">
                    @error('judul')
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            {{ $message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    @enderror
                    @error('isi')
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            {{ $message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    @enderror
                    @error('tanggal_dibuat')
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            {{ $message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    @enderror
                    @error('tanggal_diperbaharui')
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            {{ $message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    @enderror
                    <div class="form-group">
                        <label for="judul">Judul Pertanyaan</label>
                        <input type="text" class="form-control" id="judul" name="judul" value="{{ old('judul', $pertanyaan->judul) }}" placeholder="Masukkan Judul">
                        {{-- @error('judul')
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                {{ $message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @enderror --}}
                    </div>
                    <div class="form-group">
                        <label for="isi">Isi Pertanyaan</label>
                        <textarea class="form-control" name="isi" id="isi" rows="5" placeholder="Masukkan Isi">{{ old('isi', $pertanyaan->isi) }}</textarea>
                        {{-- @error('isi')
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                {{ $message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @enderror --}}
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <!-- textarea -->
                            <div class="form-group">
                                <label for="tanggal_dibuat">Tanggal Dibuat</label>
                                <input type="date" class="form-control" id="tanggal_dibuat" name="tanggal_dibuat"
                                    value="{{ old('tanggal_dibuat', date('Y-m-d', strtotime($pertanyaan->tanggal_dibuat))) }}" placeholder="Masukkan Tanggal Dibuat">
                                {{-- @error('tanggal_dibuat')
                                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                        {{ $message }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                @enderror --}}
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="tanggal_diperbaharui">Tanggal Diperbaharui</label>
                                <input type="date" class="form-control" id="tanggal_diperbaharui" name="tanggal_diperbaharui" 
                                    value="{{ old('tanggal_diperbaharui', date('Y-m-d', strtotime($pertanyaan->tanggal_diperbaharui))) }}" placeholder="Masukkan Tanggal Diperbaharui">
                                {{-- @error('tanggal_diperbaharui')
                                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                        {{ $message }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                @enderror --}}
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="jawaban_tepat_id">ID Jawaban Tepat</label>
                        <input type="number" class="form-control" id="jawaban_tepat_id" name="jawaban_tepat_id"
                            value="{{ old('jawaban_tepat_id', $pertanyaan->jawaban_tepat_id) }}" placeholder="Masukkan ID Jawaban Tepat">
                        {{-- @error('jawaban_tepat_id')
                                <div class="alert alert-danger">{{ $message }}</div>
                    @enderror --}}
                    </div>
                    <div class="form-group">
                        <label for="profil_id">ID Profil</label>
                        <input type="number" class="form-control" id="profil_id" name="profil_id"
                            value="{{ old('profil_id', $pertanyaan->profil_id) }}" placeholder="Masukkan ID Profil">
                        {{-- @error('profil_id')
                                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror --}}
                    </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                    <a class="btn btn-warning mr-1" href="{{ route('pertanyaan.index') }}">Batal</a>
                    <button type="submit" class="btn btn-primary">Update</button>
                </div>
            </form>
        </div>
    </div>
@endsection